version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - backend
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    image: confluentinc/cp-kafka:latest
    hostname: kafka0
    networks:
      - backend
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://kafka0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    networks:
      - backend
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29093,PLAINTEXT_HOST://kafka1:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - backend
    depends_on:
      - kafka0
      - kafka1
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092,kafka1:29093

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_ZOOKEEPERCONNECT: zookeeper:2181
      KAFKA_CLUSTERS_0_SECURITYPROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_SASLMECHANISM: PLAIN
      KAFKA_CLUSTERS_1_NAME: local1
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka1:29093
      KAFKA_CLUSTERS_1_ZOOKEEPERCONNECT: zookeeper:2181
      KAFKA_CLUSTERS_1_SECURITYPROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_1_SASLMECHANISM: PLAIN

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8082:80" 
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@businessid.net
      PGADMIN_DEFAULT_PASSWORD: admin

networks:
  backend:
    external:
      name: backend
